/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c6c3",
        background: "#fbf9f8",
        "on-surface-variant": "#44474d",
        surface: "#fbf9f8",
        "on-tertiary-container": "#979693",
        "primary-fixed-dim": "#b3c8eb",
        "error-container": "#ffdad6",
        "inverse-primary": "#b3c8eb",
        "surface-variant": "#e4e2e2",
        "surface-bright": "#fbf9f8",
        "outline-variant": "#c4c6ce",
        "surface-container-high": "#eae8e7",
        "tertiary-container": "#2e2f2d",
        "surface-tint": "#4b5f7e",
        "surface-container-highest": "#e4e2e2",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dbd9d9",
        "on-primary": "#ffffff",
        tertiary: "#191a18",
        "on-background": "#1b1c1c",
        "on-surface": "#1b1c1c",
        "on-primary-fixed": "#041c37",
        secondary: "#735c00",
        "surface-container": "#efeded",
        "on-secondary-fixed-variant": "#574500",
        "on-primary-container": "#8397b8",
        "on-secondary-fixed": "#241a00",
        "on-secondary-container": "#745c00",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2f0f0",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d4e3ff",
        outline: "#74777e",
        "primary-container": "#1a2f4b",
        "on-tertiary-fixed-variant": "#474744",
        "secondary-fixed": "#ffe088",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "surface-container-low": "#f5f3f3",
        "secondary-container": "#fed65b",
        "inverse-surface": "#303030",
        "on-tertiary-fixed": "#1b1c1a",
        "on-primary-fixed-variant": "#334865",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e4e2de",
        "secondary-fixed-dim": "#e9c349",
        primary: "#021a35",
        "decorative-bg": "#fdfaf8",
      },
      borderRadius: {
        DEFAULT: "2px",
        lg: "4px",
        xl: "8px",
        full: "12px",
      },
      spacing: {
        "margin-desktop": 64,
        "container-max": 1200,
        "margin-mobile": 20,
        gutter: 24,
        unit: 8,
      },
      fontFamily: {
        "headline-md": ["GHEAGrapalat-Bold"],
        "body-md": ["GHEAGrapalat-Regular"],
        "citation-xl": ["GHEAGrapalat-Italic"],
        "label-sm": ["GHEAGrapalat-Bold"],
        "display-lg-mobile": ["GHEAGrapalat-Bold"],
        "display-lg": ["GHEAGrapalat-Bold"],
        "body-lg": ["GHEAGrapalat-Regular"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "citation-xl": ["22px", { lineHeight: "36px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.6px", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.96px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
