/** M3 color tokens from client/design mockups (Digital Sanctuary). */
export const colors = {
  tertiaryFixedDim: "#c8c6c3",
  background: "#fbf9f8",
  onSurfaceVariant: "#44474d",
  surface: "#fbf9f8",
  onTertiaryContainer: "#979693",
  primaryFixedDim: "#b3c8eb",
  errorContainer: "#ffdad6",
  inversePrimary: "#b3c8eb",
  surfaceVariant: "#e4e2e2",
  surfaceBright: "#fbf9f8",
  outlineVariant: "#c4c6ce",
  surfaceContainerHigh: "#eae8e7",
  tertiaryContainer: "#2e2f2d",
  surfaceTint: "#4b5f7e",
  surfaceContainerHighest: "#e4e2e2",
  onTertiary: "#ffffff",
  surfaceDim: "#dbd9d9",
  onPrimary: "#ffffff",
  tertiary: "#191a18",
  onBackground: "#1b1c1c",
  onSurface: "#1b1c1c",
  onPrimaryFixed: "#041c37",
  secondary: "#735c00",
  surfaceContainer: "#efeded",
  onSecondaryFixedVariant: "#574500",
  onPrimaryContainer: "#8397b8",
  onSecondaryFixed: "#241a00",
  onSecondaryContainer: "#745c00",
  onErrorContainer: "#93000a",
  inverseOnSurface: "#f2f0f0",
  surfaceContainerLowest: "#ffffff",
  primaryFixed: "#d4e3ff",
  outline: "#74777e",
  primaryContainer: "#1a2f4b",
  onTertiaryFixedVariant: "#474744",
  secondaryFixed: "#ffe088",
  onError: "#ffffff",
  error: "#ba1a1a",
  surfaceContainerLow: "#f5f3f3",
  secondaryContainer: "#fed65b",
  inverseSurface: "#303030",
  onTertiaryFixed: "#1b1c1a",
  onPrimaryFixedVariant: "#334865",
  onSecondary: "#ffffff",
  tertiaryFixed: "#e4e2de",
  secondaryFixedDim: "#e9c349",
  primary: "#021a35",
  decorativeBg: "#fdfaf8",
} as const;

export const shadowLevel1 = {
  boxShadow: "0 4px 20px rgba(2, 26, 53, 0.15)",
} as const;
